export const CONSTANTS = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',

  DEEP_LINK_REQUESTED: 'DEEP_LINK_REQUESTED',
  DEEP_LINK_SUCCEEDED: 'DEEP_LINK_SUCCEEDED',
  DEEP_LINK_FAILED: 'DEEP_LINK_FAILED',

  SIGNUP_REQUESTED: 'SIGNUP_REQUESTED',
  SIGNUP_SUCCEEDED: 'SIGNUP_SUCCEEDED',
  SIGNUP_FAILED: 'SIGNUP_FAILED',

  SIGNIN_REQUESTED: 'SIGNIN_REQUESTED',
  SIGNIN_SUCCEEDED: 'SIGNIN_SUCCEEDED',
  SIGNIN_FAILED: 'SIGNIN_FAILED',

  SIGNOUT_REQUESTED: 'SIGNOUT_REQUESTED',
  SIGNOUT_SUCCEEDED: 'SIGNOUT_SUCCEEDED',
  SIGNOUT_FAILED: 'SIGNOUT_FAILED',

  RESET_PASSWORD_REQUESTED: 'RESET_PASSWORD_REQUESTED',
  RESET_PASSWORD_SUCCEEDED: 'RESET_PASSWORD_SUCCEEDED',
  RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',

  FORGOT_REQUESTED: 'FORGOT_REQUESTED',
  FORGOT_SUCCEEDED: 'FORGOT_SUCCEEDED',
  FORGOT_FAILED: 'FORGOT_FAILED',

  GOOGLE_LOGIN_REQUESTED: 'GOOGLE_LOGIN_REQUESTED',
  GOOGLE_LOGIN_SUCCEEDED: 'GOOGLE_LOGIN_SUCCEEDED',
  GOOGLE_LOGIN_FAILED: 'GOOGLE_LOGIN_FAILED',

  FB_LOGIN_REQUESTED: 'FB_LOGIN_REQUESTED',
  FB_LOGIN_SUCCEEDED: 'FB_LOGIN_SUCCEEDED',
  FB_LOGIN_FAILED: 'FB_LOGIN_FAILED',

  CLEAR_ERROR: 'CLEAR_ERROR',

  LOGOUT: 'LOGOUT',
};
