export const ROUTES = {
  SIGNIN: 'SignIn',
  SIGNUP: 'SignUp',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  CHECK_EMAIL: 'CheckEmail',
  OPEN_EMAIL: 'OpenEmail',
  UPDATE_PASSWORD: 'UpdatePassword',
  HOME: 'Home',
  TECH_NEWS_TAB:'TechNewsTab',
  TECH_NEWS:'TechNews',
  HAPPENING_TAB: 'HappeningTab',
  HAPPENING: 'Happening',
  HAPPENING_EVENT_DETAIL: 'HappeningEventDetail',
  PREFACE_TAB:'PrefaceTab',
  PREFACE:'Preface',
  NOTIFICATION_TAB: 'NotificationTab',
  NOTIFICATION: 'Notification',
  PROFILE_TAB: 'ProfileTab',
  PROFILE: 'Profile'
};
