export const EVENT = {
  CURRENT_GET_ALL_EVENT_REQUESTED: 'CURRENT_GET_ALL_EVENT_REQUESTED',
  CURRENT_GET_ALL_EVENT_SUCCEEDED: 'CURRENT_GET_ALL_EVENT_SUCCEEDED',
  CURRENT_GET_ALL_EVENT_FAILED: 'CURRENT_GET_ALL_EVENT_FAILED',
};
