export const EVENT = {
  CURRENT_GET_ALL_EVENT_REQUESTED: 'CURRENT_GET_ALL_EVENT_REQUESTED',
  CURRENT_GET_ALL_EVENT_SUCCEEDED: 'CURRENT_GET_ALL_EVENT_SUCCEEDED',
  CURRENT_GET_ALL_EVENT_FAILED: 'CURRENT_GET_ALL_EVENT_FAILED',

  GET_STRUCTURED_CONTENT_REQUESTED:'GET_STRUCTURED_CONTENT_REQUEST',
  GET_STRUCTURED_CONTENT_SUCCEEDED:'GET_STRUCTURED_CONTENT_SUCCEEDED',
  GET_STRUCTURED_CONTENT_FAILED:'GET_STRUCTURED_CONTENT_FAILED',
};
